#!/usr/bin/env node
/**
 * scripts/sync-modules.mjs
 *
 * modules/<name>/frontend/{lib,routes}/ を frontend/src/ にコピーして同期する。
 * - modules/<name>/frontend/lib/   → frontend/src/lib/modules/<name>/
 * - modules/<name>/frontend/routes/ → frontend/src/routes/                （配下を直接マージ）
 *
 * 同期されたファイルの先頭にはマーカーコメントを付け、人間/Claude が「これは生成物だ」と
 * 認識できるようにする。同期先は .gitignore の対象（再生成可能）。
 *
 * 使い方:
 *   node scripts/sync-modules.mjs              # 通常実行
 *   node scripts/sync-modules.mjs --check      # 同期されているか確認のみ（差分があれば exit 1）
 */
import { existsSync, readFileSync, statSync, writeFileSync } from 'node:fs';
import { cp, mkdir, readdir, rm } from 'node:fs/promises';
import { dirname, join, relative, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const SCRIPT_DIR = dirname(fileURLToPath(import.meta.url));
const ROOT = resolve(SCRIPT_DIR, '..');
const MODULES_DIR = join(ROOT, 'modules');
const FRONTEND_SRC = join(ROOT, 'frontend', 'src');
const LIB_DEST_BASE = join(FRONTEND_SRC, 'lib', 'modules');
const ROUTES_DEST_BASE = join(FRONTEND_SRC, 'routes');

const MARKER = '/* AUTO-GENERATED by scripts/sync-modules.mjs — DO NOT EDIT directly. Edit modules/<name>/frontend/. */\n';

const checkMode = process.argv.includes('--check');

async function listModules() {
  if (!existsSync(MODULES_DIR)) return [];
  const entries = await readdir(MODULES_DIR, { withFileTypes: true });
  return entries
    .filter((e) => e.isDirectory() && !e.name.startsWith('.') && !e.name.startsWith('_'))
    .map((e) => e.name)
    .sort();
}

async function copyTree(src, dest) {
  if (!existsSync(src)) return [];
  await rm(dest, { recursive: true, force: true });
  await mkdir(dest, { recursive: true });
  await cp(src, dest, { recursive: true });

  // マーカーを各テキストファイルに前置
  const stamped = [];
  await stampDir(dest, stamped);
  return stamped;
}

async function stampDir(dir, acc) {
  const entries = await readdir(dir, { withFileTypes: true });
  for (const e of entries) {
    const full = join(dir, e.name);
    if (e.isDirectory()) {
      await stampDir(full, acc);
    } else if (/\.(svelte|ts|tsx|js|mjs|css)$/.test(e.name)) {
      const content = readFileSync(full, 'utf-8');
      if (!content.startsWith('/* AUTO-GENERATED')) {
        writeFileSync(full, MARKER + content, 'utf-8');
      }
      acc.push(relative(ROOT, full));
    }
  }
}

async function main() {
  const modules = await listModules();
  const synced = [];

  for (const name of modules) {
    const moduleFrontend = join(MODULES_DIR, name, 'frontend');
    if (!existsSync(moduleFrontend)) continue;

    const libSrc = join(moduleFrontend, 'lib');
    const libDest = join(LIB_DEST_BASE, name);
    if (existsSync(libSrc)) {
      const files = await copyTree(libSrc, libDest);
      synced.push(...files);
      console.log(`  lib:    modules/${name}/frontend/lib/  →  frontend/src/lib/modules/${name}/  (${files.length} files)`);
    }

    const routesSrc = join(moduleFrontend, 'routes');
    if (existsSync(routesSrc)) {
      // routes は名前空間化せず直接マージ（SvelteKit のファイルベースルーティング規約のため）
      const subDirs = await readdir(routesSrc, { withFileTypes: true });
      for (const sub of subDirs) {
        if (!sub.isDirectory()) continue;
        const subSrc = join(routesSrc, sub.name);
        const subDest = join(ROUTES_DEST_BASE, sub.name);
        const files = await copyTree(subSrc, subDest);
        synced.push(...files);
        console.log(`  route:  modules/${name}/frontend/routes/${sub.name}/  →  frontend/src/routes/${sub.name}/  (${files.length} files)`);
      }
    }
  }

  if (synced.length === 0) {
    console.log('no module frontend files to sync.');
    return 0;
  }

  if (checkMode) {
    // 完全な再生成と比較する代わりに、上のコピーで上書きしたので
    // 差分検出は git に任せる前提（git status -s | grep frontend/src/lib/modules）。
    console.log(`\nsynced ${synced.length} files (check mode)`);
  } else {
    console.log(`\nsynced ${synced.length} files`);
  }
  return 0;
}

main().then((code) => process.exit(code)).catch((err) => {
  console.error(err);
  process.exit(1);
});
